channels:
- conda-forge
dependencies:
- python=3.10.13
- pip<=24.0
- pip:
  - mlflow==2.4
  - cloudpickle==2.2.1
  - psutil==5.9.5
  - scikit-learn==1.4.1.post1
  - typing-extensions==4.1.1
name: mlflow-env
